/*
 * This file is generated by jOOQ.
 */
package com.madera.jooq;


import com.madera.jooq.tables.Adresse;
import com.madera.jooq.tables.Client;
import com.madera.jooq.tables.ClientAdresse;
import com.madera.jooq.tables.Composant;
import com.madera.jooq.tables.ComposantFournisseur;
import com.madera.jooq.tables.ComposantGroupe;
import com.madera.jooq.tables.ComposantReferentiel;
import com.madera.jooq.tables.DevisEtat;
import com.madera.jooq.tables.Fournisseur;
import com.madera.jooq.tables.Gammes;
import com.madera.jooq.tables.Module;
import com.madera.jooq.tables.ModuleComposant;
import com.madera.jooq.tables.ModuleReferentiel;
import com.madera.jooq.tables.Projet;
import com.madera.jooq.tables.ProjetModule;
import com.madera.jooq.tables.ProjetUtilisateurs;
import com.madera.jooq.tables.Role;
import com.madera.jooq.tables.Utilisateur;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>madera</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADRESSE_PKEY = Indexes0.ADRESSE_PKEY;
    public static final Index CLIENT_PKEY = Indexes0.CLIENT_PKEY;
    public static final Index FK_ADRESSE_IDX_2 = Indexes0.FK_ADRESSE_IDX_2;
    public static final Index COMPOSANT_PKEY = Indexes0.COMPOSANT_PKEY;
    public static final Index FK_COMPOSANT_GROUPE_IDX = Indexes0.FK_COMPOSANT_GROUPE_IDX;
    public static final Index FK_COMPOSANT_REFERENTIEL_IDX = Indexes0.FK_COMPOSANT_REFERENTIEL_IDX;
    public static final Index COMPOSANT_FOURNISSEUR_PKEY = Indexes0.COMPOSANT_FOURNISSEUR_PKEY;
    public static final Index FK_FOURNISSEUR_IDX = Indexes0.FK_FOURNISSEUR_IDX;
    public static final Index COMPOSANT_GROUPE_PKEY = Indexes0.COMPOSANT_GROUPE_PKEY;
    public static final Index COMPOSANT_REFERENTIEL_PKEY = Indexes0.COMPOSANT_REFERENTIEL_PKEY;
    public static final Index DEVIS_ETAT_PKEY = Indexes0.DEVIS_ETAT_PKEY;
    public static final Index FK_ADRESSE_IDX = Indexes0.FK_ADRESSE_IDX;
    public static final Index FOURNISSEUR_PKEY = Indexes0.FOURNISSEUR_PKEY;
    public static final Index GAMMES_PKEY = Indexes0.GAMMES_PKEY;
    public static final Index FK_GAMMES_IDX = Indexes0.FK_GAMMES_IDX;
    public static final Index FK_MODULE_REFERENTIEL_IDX = Indexes0.FK_MODULE_REFERENTIEL_IDX;
    public static final Index MODULE_PKEY = Indexes0.MODULE_PKEY;
    public static final Index FK_COMPOSANT_IDX = Indexes0.FK_COMPOSANT_IDX;
    public static final Index MODULE_REFERENTIEL_PKEY = Indexes0.MODULE_REFERENTIEL_PKEY;
    public static final Index FK_CLIENT_IDX = Indexes0.FK_CLIENT_IDX;
    public static final Index PROJET_PKEY = Indexes0.PROJET_PKEY;
    public static final Index FK_MODULE_IDX = Indexes0.FK_MODULE_IDX;
    public static final Index FK_PROJET_IDX_3 = Indexes0.FK_PROJET_IDX_3;
    public static final Index PROJET_MODULE_PKEY = Indexes0.PROJET_MODULE_PKEY;
    public static final Index FK_PROJET_IDX_2 = Indexes0.FK_PROJET_IDX_2;
    public static final Index ROLE_PKEY = Indexes0.ROLE_PKEY;
    public static final Index FK_ROLE_IDX = Indexes0.FK_ROLE_IDX;
    public static final Index UTILISATEUR_PKEY = Indexes0.UTILISATEUR_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ADRESSE_PKEY = Internal.createIndex("adresse_pkey", Adresse.ADRESSE, new OrderField[] { Adresse.ADRESSE.I_ADRESSE_ID }, true);
        public static Index CLIENT_PKEY = Internal.createIndex("client_pkey", Client.CLIENT, new OrderField[] { Client.CLIENT.I_CLIENT_ID }, true);
        public static Index FK_ADRESSE_IDX_2 = Internal.createIndex("fk_adresse_idx_2", ClientAdresse.CLIENT_ADRESSE, new OrderField[] { ClientAdresse.CLIENT_ADRESSE.I_ADRESSE_ID }, false);
        public static Index COMPOSANT_PKEY = Internal.createIndex("composant_pkey", Composant.COMPOSANT, new OrderField[] { Composant.COMPOSANT.I_COMPOSANT_ID }, true);
        public static Index FK_COMPOSANT_GROUPE_IDX = Internal.createIndex("fk_composant_groupe_idx", Composant.COMPOSANT, new OrderField[] { Composant.COMPOSANT.I_COMPOSANT_GROUPE_ID }, false);
        public static Index FK_COMPOSANT_REFERENTIEL_IDX = Internal.createIndex("fk_composant_referentiel_idx", Composant.COMPOSANT, new OrderField[] { Composant.COMPOSANT.I_COMPOSANT_REFERENTIEL_ID }, false);
        public static Index COMPOSANT_FOURNISSEUR_PKEY = Internal.createIndex("composant_fournisseur_pkey", ComposantFournisseur.COMPOSANT_FOURNISSEUR, new OrderField[] { ComposantFournisseur.COMPOSANT_FOURNISSEUR.I_FOURNISSEUR_ID, ComposantFournisseur.COMPOSANT_FOURNISSEUR.I_COMPOSANT_ID }, true);
        public static Index FK_FOURNISSEUR_IDX = Internal.createIndex("fk_fournisseur_idx", ComposantFournisseur.COMPOSANT_FOURNISSEUR, new OrderField[] { ComposantFournisseur.COMPOSANT_FOURNISSEUR.I_FOURNISSEUR_ID }, false);
        public static Index COMPOSANT_GROUPE_PKEY = Internal.createIndex("composant_groupe_pkey", ComposantGroupe.COMPOSANT_GROUPE, new OrderField[] { ComposantGroupe.COMPOSANT_GROUPE.I_COMPOSANT_GROUPE_ID }, true);
        public static Index COMPOSANT_REFERENTIEL_PKEY = Internal.createIndex("composant_referentiel_pkey", ComposantReferentiel.COMPOSANT_REFERENTIEL, new OrderField[] { ComposantReferentiel.COMPOSANT_REFERENTIEL.I_COMPOSANT_REFERENTIEL_ID }, true);
        public static Index DEVIS_ETAT_PKEY = Internal.createIndex("devis_etat_pkey", DevisEtat.DEVIS_ETAT, new OrderField[] { DevisEtat.DEVIS_ETAT.I_DEVIS_ETAT_ID }, true);
        public static Index FK_ADRESSE_IDX = Internal.createIndex("fk_adresse_idx", Fournisseur.FOURNISSEUR, new OrderField[] { Fournisseur.FOURNISSEUR.I_ADRESSE_ID }, false);
        public static Index FOURNISSEUR_PKEY = Internal.createIndex("fournisseur_pkey", Fournisseur.FOURNISSEUR, new OrderField[] { Fournisseur.FOURNISSEUR.I_FOURNISSEUR_ID }, true);
        public static Index GAMMES_PKEY = Internal.createIndex("gammes_pkey", Gammes.GAMMES, new OrderField[] { Gammes.GAMMES.I_GAMMES_ID }, true);
        public static Index FK_GAMMES_IDX = Internal.createIndex("fk_gammes_idx", Module.MODULE, new OrderField[] { Module.MODULE.I_GAMMES_ID }, false);
        public static Index FK_MODULE_REFERENTIEL_IDX = Internal.createIndex("fk_module_referentiel_idx", Module.MODULE, new OrderField[] { Module.MODULE.I_MODULE_REFERENTIEL_ID }, false);
        public static Index MODULE_PKEY = Internal.createIndex("module_pkey", Module.MODULE, new OrderField[] { Module.MODULE.I_MODULE_ID }, true);
        public static Index FK_COMPOSANT_IDX = Internal.createIndex("fk_composant_idx", ModuleComposant.MODULE_COMPOSANT, new OrderField[] { ModuleComposant.MODULE_COMPOSANT.I_COMPOSANT_ID }, false);
        public static Index MODULE_REFERENTIEL_PKEY = Internal.createIndex("module_referentiel_pkey", ModuleReferentiel.MODULE_REFERENTIEL, new OrderField[] { ModuleReferentiel.MODULE_REFERENTIEL.I_MODULE_REFERENTIEL_ID }, true);
        public static Index FK_CLIENT_IDX = Internal.createIndex("fk_client_idx", Projet.PROJET, new OrderField[] { Projet.PROJET.I_CLIENT_ID }, false);
        public static Index PROJET_PKEY = Internal.createIndex("projet_pkey", Projet.PROJET, new OrderField[] { Projet.PROJET.I_PROJET_ID }, true);
        public static Index FK_MODULE_IDX = Internal.createIndex("fk_module_idx", ProjetModule.PROJET_MODULE, new OrderField[] { ProjetModule.PROJET_MODULE.I_MODULE_ID }, false);
        public static Index FK_PROJET_IDX_3 = Internal.createIndex("fk_projet_idx_3", ProjetModule.PROJET_MODULE, new OrderField[] { ProjetModule.PROJET_MODULE.I_PROJET_ID }, false);
        public static Index PROJET_MODULE_PKEY = Internal.createIndex("projet_module_pkey", ProjetModule.PROJET_MODULE, new OrderField[] { ProjetModule.PROJET_MODULE.I_PROJET_MODULE_ID }, true);
        public static Index FK_PROJET_IDX_2 = Internal.createIndex("fk_projet_idx_2", ProjetUtilisateurs.PROJET_UTILISATEURS, new OrderField[] { ProjetUtilisateurs.PROJET_UTILISATEURS.I_PROJET_ID }, false);
        public static Index ROLE_PKEY = Internal.createIndex("role_pkey", Role.ROLE, new OrderField[] { Role.ROLE.I_ROLE_ID }, true);
        public static Index FK_ROLE_IDX = Internal.createIndex("fk_role_idx", Utilisateur.UTILISATEUR, new OrderField[] { Utilisateur.UTILISATEUR.I_ROLE_ID }, false);
        public static Index UTILISATEUR_PKEY = Internal.createIndex("utilisateur_pkey", Utilisateur.UTILISATEUR, new OrderField[] { Utilisateur.UTILISATEUR.I_UTILISATEUR_ID }, true);
    }
}
