/*
 * This file is generated by jOOQ.
 */
package com.madera.jooq;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in madera
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>madera.adresse_i_adresse_id_seq</code>
     */
    public static final Sequence<Integer> ADRESSE_I_ADRESSE_ID_SEQ = new SequenceImpl<Integer>("adresse_i_adresse_id_seq", Madera.MADERA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>madera.client_i_client_id_seq</code>
     */
    public static final Sequence<Integer> CLIENT_I_CLIENT_ID_SEQ = new SequenceImpl<Integer>("client_i_client_id_seq", Madera.MADERA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>madera.composant_groupe_i_composant_groupe_id_seq</code>
     */
    public static final Sequence<Integer> COMPOSANT_GROUPE_I_COMPOSANT_GROUPE_ID_SEQ = new SequenceImpl<Integer>("composant_groupe_i_composant_groupe_id_seq", Madera.MADERA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>madera.composant_i_composant_id_seq</code>
     */
    public static final Sequence<Integer> COMPOSANT_I_COMPOSANT_ID_SEQ = new SequenceImpl<Integer>("composant_i_composant_id_seq", Madera.MADERA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>madera.composant_referentiel_i_composant_referentiel_id_seq</code>
     */
    public static final Sequence<Integer> COMPOSANT_REFERENTIEL_I_COMPOSANT_REFERENTIEL_ID_SEQ = new SequenceImpl<Integer>("composant_referentiel_i_composant_referentiel_id_seq", Madera.MADERA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>madera.devis_etat_i_devis_etat_id_seq</code>
     */
    public static final Sequence<Integer> DEVIS_ETAT_I_DEVIS_ETAT_ID_SEQ = new SequenceImpl<Integer>("devis_etat_i_devis_etat_id_seq", Madera.MADERA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>madera.fournisseur_i_fournisseur_id_seq</code>
     */
    public static final Sequence<Integer> FOURNISSEUR_I_FOURNISSEUR_ID_SEQ = new SequenceImpl<Integer>("fournisseur_i_fournisseur_id_seq", Madera.MADERA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>madera.gammes_i_gammes_id_seq</code>
     */
    public static final Sequence<Integer> GAMMES_I_GAMMES_ID_SEQ = new SequenceImpl<Integer>("gammes_i_gammes_id_seq", Madera.MADERA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>madera.module_i_module_id_seq</code>
     */
    public static final Sequence<Integer> MODULE_I_MODULE_ID_SEQ = new SequenceImpl<Integer>("module_i_module_id_seq", Madera.MADERA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>madera.module_referentiel_i_module_referentiel_id_seq</code>
     */
    public static final Sequence<Integer> MODULE_REFERENTIEL_I_MODULE_REFERENTIEL_ID_SEQ = new SequenceImpl<Integer>("module_referentiel_i_module_referentiel_id_seq", Madera.MADERA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>madera.produit_i_produit_id_seq</code>
     */
    public static final Sequence<Integer> PRODUIT_I_PRODUIT_ID_SEQ = new SequenceImpl<Integer>("produit_i_produit_id_seq", Madera.MADERA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>madera.produit_module_i_produit_module_id_seq</code>
     */
    public static final Sequence<Integer> PRODUIT_MODULE_I_PRODUIT_MODULE_ID_SEQ = new SequenceImpl<Integer>("produit_module_i_produit_module_id_seq", Madera.MADERA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>madera.projet_i_projet_id_seq</code>
     */
    public static final Sequence<Integer> PROJET_I_PROJET_ID_SEQ = new SequenceImpl<Integer>("projet_i_projet_id_seq", Madera.MADERA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>madera.role_i_role_id_seq</code>
     */
    public static final Sequence<Integer> ROLE_I_ROLE_ID_SEQ = new SequenceImpl<Integer>("role_i_role_id_seq", Madera.MADERA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>madera.utilisateur_i_utilisateur_id_seq</code>
     */
    public static final Sequence<Integer> UTILISATEUR_I_UTILISATEUR_ID_SEQ = new SequenceImpl<Integer>("utilisateur_i_utilisateur_id_seq", Madera.MADERA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
