/*
 * This file is generated by jOOQ.
 */
package com.madera.jooq;


import com.madera.jooq.tables.Adresse;
import com.madera.jooq.tables.Client;
import com.madera.jooq.tables.ClientAdresse;
import com.madera.jooq.tables.Composant;
import com.madera.jooq.tables.ComposantFournisseur;
import com.madera.jooq.tables.ComposantGroupe;
import com.madera.jooq.tables.ComposantReferentiel;
import com.madera.jooq.tables.DevisEtat;
import com.madera.jooq.tables.Fournisseur;
import com.madera.jooq.tables.Gammes;
import com.madera.jooq.tables.Module;
import com.madera.jooq.tables.ModuleComposant;
import com.madera.jooq.tables.ModuleReferentiel;
import com.madera.jooq.tables.Projet;
import com.madera.jooq.tables.ProjetModule;
import com.madera.jooq.tables.ProjetUtilisateurs;
import com.madera.jooq.tables.Role;
import com.madera.jooq.tables.Utilisateur;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in madera
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>madera.adresse</code>.
     */
    public static final Adresse ADRESSE = Adresse.ADRESSE;

    /**
     * The table <code>madera.client</code>.
     */
    public static final Client CLIENT = Client.CLIENT;

    /**
     * The table <code>madera.client_adresse</code>.
     */
    public static final ClientAdresse CLIENT_ADRESSE = ClientAdresse.CLIENT_ADRESSE;

    /**
     * The table <code>madera.composant</code>.
     */
    public static final Composant COMPOSANT = Composant.COMPOSANT;

    /**
     * The table <code>madera.composant_fournisseur</code>.
     */
    public static final ComposantFournisseur COMPOSANT_FOURNISSEUR = ComposantFournisseur.COMPOSANT_FOURNISSEUR;

    /**
     * The table <code>madera.composant_groupe</code>.
     */
    public static final ComposantGroupe COMPOSANT_GROUPE = ComposantGroupe.COMPOSANT_GROUPE;

    /**
     * The table <code>madera.composant_referentiel</code>.
     */
    public static final ComposantReferentiel COMPOSANT_REFERENTIEL = ComposantReferentiel.COMPOSANT_REFERENTIEL;

    /**
     * The table <code>madera.devis_etat</code>.
     */
    public static final DevisEtat DEVIS_ETAT = DevisEtat.DEVIS_ETAT;

    /**
     * The table <code>madera.fournisseur</code>.
     */
    public static final Fournisseur FOURNISSEUR = Fournisseur.FOURNISSEUR;

    /**
     * The table <code>madera.gammes</code>.
     */
    public static final Gammes GAMMES = Gammes.GAMMES;

    /**
     * The table <code>madera.module</code>.
     */
    public static final Module MODULE = Module.MODULE;

    /**
     * The table <code>madera.module_composant</code>.
     */
    public static final ModuleComposant MODULE_COMPOSANT = ModuleComposant.MODULE_COMPOSANT;

    /**
     * The table <code>madera.module_referentiel</code>.
     */
    public static final ModuleReferentiel MODULE_REFERENTIEL = ModuleReferentiel.MODULE_REFERENTIEL;

    /**
     * The table <code>madera.projet</code>.
     */
    public static final Projet PROJET = Projet.PROJET;

    /**
     * The table <code>madera.projet_module</code>.
     */
    public static final ProjetModule PROJET_MODULE = ProjetModule.PROJET_MODULE;

    /**
     * The table <code>madera.projet_utilisateurs</code>.
     */
    public static final ProjetUtilisateurs PROJET_UTILISATEURS = ProjetUtilisateurs.PROJET_UTILISATEURS;

    /**
     * The table <code>madera.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>madera.utilisateur</code>.
     */
    public static final Utilisateur UTILISATEUR = Utilisateur.UTILISATEUR;
}
