/*
 * This file is generated by jOOQ.
 */
package org.jooq.model.madera;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.jooq.model.madera.tables.Adresse;
import org.jooq.model.madera.tables.Client;
import org.jooq.model.madera.tables.ClientAdresse;
import org.jooq.model.madera.tables.Composant;
import org.jooq.model.madera.tables.ComposantFournisseur;
import org.jooq.model.madera.tables.ComposantGroupe;
import org.jooq.model.madera.tables.ComposantReferentiel;
import org.jooq.model.madera.tables.DevisEtat;
import org.jooq.model.madera.tables.Fournisseur;
import org.jooq.model.madera.tables.Gammes;
import org.jooq.model.madera.tables.Module;
import org.jooq.model.madera.tables.ModuleComposant;
import org.jooq.model.madera.tables.ModuleReferentiel;
import org.jooq.model.madera.tables.Projet;
import org.jooq.model.madera.tables.ProjetModule;
import org.jooq.model.madera.tables.ProjetUtilisateurs;
import org.jooq.model.madera.tables.Role;
import org.jooq.model.madera.tables.Utilisateur;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Madera extends SchemaImpl {

    private static final long serialVersionUID = 327667866;

    /**
     * The reference instance of <code>madera</code>
     */
    public static final Madera MADERA = new Madera();

    /**
     * The table <code>madera.adresse</code>.
     */
    public final Adresse ADRESSE = org.jooq.model.madera.tables.Adresse.ADRESSE;

    /**
     * The table <code>madera.client</code>.
     */
    public final Client CLIENT = org.jooq.model.madera.tables.Client.CLIENT;

    /**
     * The table <code>madera.client_adresse</code>.
     */
    public final ClientAdresse CLIENT_ADRESSE = org.jooq.model.madera.tables.ClientAdresse.CLIENT_ADRESSE;

    /**
     * The table <code>madera.composant</code>.
     */
    public final Composant COMPOSANT = org.jooq.model.madera.tables.Composant.COMPOSANT;

    /**
     * The table <code>madera.composant_fournisseur</code>.
     */
    public final ComposantFournisseur COMPOSANT_FOURNISSEUR = org.jooq.model.madera.tables.ComposantFournisseur.COMPOSANT_FOURNISSEUR;

    /**
     * The table <code>madera.composant_groupe</code>.
     */
    public final ComposantGroupe COMPOSANT_GROUPE = org.jooq.model.madera.tables.ComposantGroupe.COMPOSANT_GROUPE;

    /**
     * The table <code>madera.composant_referentiel</code>.
     */
    public final ComposantReferentiel COMPOSANT_REFERENTIEL = org.jooq.model.madera.tables.ComposantReferentiel.COMPOSANT_REFERENTIEL;

    /**
     * The table <code>madera.devis_etat</code>.
     */
    public final DevisEtat DEVIS_ETAT = org.jooq.model.madera.tables.DevisEtat.DEVIS_ETAT;

    /**
     * The table <code>madera.fournisseur</code>.
     */
    public final Fournisseur FOURNISSEUR = org.jooq.model.madera.tables.Fournisseur.FOURNISSEUR;

    /**
     * The table <code>madera.gammes</code>.
     */
    public final Gammes GAMMES = org.jooq.model.madera.tables.Gammes.GAMMES;

    /**
     * The table <code>madera.module</code>.
     */
    public final Module MODULE = org.jooq.model.madera.tables.Module.MODULE;

    /**
     * The table <code>madera.module_composant</code>.
     */
    public final ModuleComposant MODULE_COMPOSANT = org.jooq.model.madera.tables.ModuleComposant.MODULE_COMPOSANT;

    /**
     * The table <code>madera.module_referentiel</code>.
     */
    public final ModuleReferentiel MODULE_REFERENTIEL = org.jooq.model.madera.tables.ModuleReferentiel.MODULE_REFERENTIEL;

    /**
     * The table <code>madera.projet</code>.
     */
    public final Projet PROJET = org.jooq.model.madera.tables.Projet.PROJET;

    /**
     * The table <code>madera.projet_module</code>.
     */
    public final ProjetModule PROJET_MODULE = org.jooq.model.madera.tables.ProjetModule.PROJET_MODULE;

    /**
     * The table <code>madera.projet_utilisateurs</code>.
     */
    public final ProjetUtilisateurs PROJET_UTILISATEURS = org.jooq.model.madera.tables.ProjetUtilisateurs.PROJET_UTILISATEURS;

    /**
     * The table <code>madera.role</code>.
     */
    public final Role ROLE = org.jooq.model.madera.tables.Role.ROLE;

    /**
     * The table <code>madera.utilisateur</code>.
     */
    public final Utilisateur UTILISATEUR = org.jooq.model.madera.tables.Utilisateur.UTILISATEUR;

    /**
     * No further instances allowed
     */
    private Madera() {
        super("madera", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Adresse.ADRESSE,
            Client.CLIENT,
            ClientAdresse.CLIENT_ADRESSE,
            Composant.COMPOSANT,
            ComposantFournisseur.COMPOSANT_FOURNISSEUR,
            ComposantGroupe.COMPOSANT_GROUPE,
            ComposantReferentiel.COMPOSANT_REFERENTIEL,
            DevisEtat.DEVIS_ETAT,
            Fournisseur.FOURNISSEUR,
            Gammes.GAMMES,
            Module.MODULE,
            ModuleComposant.MODULE_COMPOSANT,
            ModuleReferentiel.MODULE_REFERENTIEL,
            Projet.PROJET,
            ProjetModule.PROJET_MODULE,
            ProjetUtilisateurs.PROJET_UTILISATEURS,
            Role.ROLE,
            Utilisateur.UTILISATEUR);
    }
}
