/*
 * This file is generated by jOOQ.
 */
package org.jooq.model.madera.tables.records;


import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.model.madera.tables.Client;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientRecord extends UpdatableRecordImpl<ClientRecord> implements Record5<Integer, String, String, String, String> {

    private static final long serialVersionUID = -1500866399;

    /**
     * Setter for <code>madera.client.i_client_id</code>.
     */
    public void setIClientId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>madera.client.i_client_id</code>.
     */
    public Integer getIClientId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>madera.client.v_nom</code>.
     */
    public void setVNom(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>madera.client.v_nom</code>.
     */
    public String getVNom() {
        return (String) get(1);
    }

    /**
     * Setter for <code>madera.client.v_prenom</code>.
     */
    public void setVPrenom(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>madera.client.v_prenom</code>.
     */
    public String getVPrenom() {
        return (String) get(2);
    }

    /**
     * Setter for <code>madera.client.v_tel</code>.
     */
    public void setVTel(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>madera.client.v_tel</code>.
     */
    public String getVTel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>madera.client.v_mail</code>.
     */
    public void setVMail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>madera.client.v_mail</code>.
     */
    public String getVMail() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Client.CLIENT.I_CLIENT_ID;
    }

    @Override
    public Field<String> field2() {
        return Client.CLIENT.V_NOM;
    }

    @Override
    public Field<String> field3() {
        return Client.CLIENT.V_PRENOM;
    }

    @Override
    public Field<String> field4() {
        return Client.CLIENT.V_TEL;
    }

    @Override
    public Field<String> field5() {
        return Client.CLIENT.V_MAIL;
    }

    @Override
    public Integer component1() {
        return getIClientId();
    }

    @Override
    public String component2() {
        return getVNom();
    }

    @Override
    public String component3() {
        return getVPrenom();
    }

    @Override
    public String component4() {
        return getVTel();
    }

    @Override
    public String component5() {
        return getVMail();
    }

    @Override
    public Integer value1() {
        return getIClientId();
    }

    @Override
    public String value2() {
        return getVNom();
    }

    @Override
    public String value3() {
        return getVPrenom();
    }

    @Override
    public String value4() {
        return getVTel();
    }

    @Override
    public String value5() {
        return getVMail();
    }

    @Override
    public ClientRecord value1(Integer value) {
        setIClientId(value);
        return this;
    }

    @Override
    public ClientRecord value2(String value) {
        setVNom(value);
        return this;
    }

    @Override
    public ClientRecord value3(String value) {
        setVPrenom(value);
        return this;
    }

    @Override
    public ClientRecord value4(String value) {
        setVTel(value);
        return this;
    }

    @Override
    public ClientRecord value5(String value) {
        setVMail(value);
        return this;
    }

    @Override
    public ClientRecord values(Integer value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientRecord
     */
    public ClientRecord() {
        super(Client.CLIENT);
    }

    /**
     * Create a detached, initialised ClientRecord
     */
    public ClientRecord(Integer iClientId, String vNom, String vPrenom, String vTel, String vMail) {
        super(Client.CLIENT);

        set(0, iClientId);
        set(1, vNom);
        set(2, vPrenom);
        set(3, vTel);
        set(4, vMail);
    }
}
