/*
 * This file is generated by jOOQ.
 */
package org.jooq.model.madera.tables.records;


import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.model.madera.tables.DevisEtat;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DevisEtatRecord extends UpdatableRecordImpl<DevisEtatRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1175269642;

    /**
     * Setter for <code>madera.devis_etat.i_devis_etat_id</code>.
     */
    public void setIDevisEtatId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>madera.devis_etat.i_devis_etat_id</code>.
     */
    public Integer getIDevisEtatId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>madera.devis_etat.v_devis_etat_libelle</code>.
     */
    public void setVDevisEtatLibelle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>madera.devis_etat.v_devis_etat_libelle</code>.
     */
    public String getVDevisEtatLibelle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>madera.devis_etat.i_pourcentage_somme</code>.
     */
    public void setIPourcentageSomme(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>madera.devis_etat.i_pourcentage_somme</code>.
     */
    public Integer getIPourcentageSomme() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DevisEtat.DEVIS_ETAT.I_DEVIS_ETAT_ID;
    }

    @Override
    public Field<String> field2() {
        return DevisEtat.DEVIS_ETAT.V_DEVIS_ETAT_LIBELLE;
    }

    @Override
    public Field<Integer> field3() {
        return DevisEtat.DEVIS_ETAT.I_POURCENTAGE_SOMME;
    }

    @Override
    public Integer component1() {
        return getIDevisEtatId();
    }

    @Override
    public String component2() {
        return getVDevisEtatLibelle();
    }

    @Override
    public Integer component3() {
        return getIPourcentageSomme();
    }

    @Override
    public Integer value1() {
        return getIDevisEtatId();
    }

    @Override
    public String value2() {
        return getVDevisEtatLibelle();
    }

    @Override
    public Integer value3() {
        return getIPourcentageSomme();
    }

    @Override
    public DevisEtatRecord value1(Integer value) {
        setIDevisEtatId(value);
        return this;
    }

    @Override
    public DevisEtatRecord value2(String value) {
        setVDevisEtatLibelle(value);
        return this;
    }

    @Override
    public DevisEtatRecord value3(Integer value) {
        setIPourcentageSomme(value);
        return this;
    }

    @Override
    public DevisEtatRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DevisEtatRecord
     */
    public DevisEtatRecord() {
        super(DevisEtat.DEVIS_ETAT);
    }

    /**
     * Create a detached, initialised DevisEtatRecord
     */
    public DevisEtatRecord(Integer iDevisEtatId, String vDevisEtatLibelle, Integer iPourcentageSomme) {
        super(DevisEtat.DEVIS_ETAT);

        set(0, iDevisEtatId);
        set(1, vDevisEtatLibelle);
        set(2, iPourcentageSomme);
    }
}
