/*
 * This file is generated by jOOQ.
 */
package org.jooq.model.madera.tables.records;


import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.model.madera.tables.Fournisseur;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FournisseurRecord extends UpdatableRecordImpl<FournisseurRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = -35636629;

    /**
     * Setter for <code>madera.fournisseur.i_fournisseur_id</code>.
     */
    public void setIFournisseurId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>madera.fournisseur.i_fournisseur_id</code>.
     */
    public Integer getIFournisseurId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>madera.fournisseur.v_raison_soc</code>.
     */
    public void setVRaisonSoc(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>madera.fournisseur.v_raison_soc</code>.
     */
    public String getVRaisonSoc() {
        return (String) get(1);
    }

    /**
     * Setter for <code>madera.fournisseur.i_adresse_id</code>.
     */
    public void setIAdresseId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>madera.fournisseur.i_adresse_id</code>.
     */
    public Integer getIAdresseId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Fournisseur.FOURNISSEUR.I_FOURNISSEUR_ID;
    }

    @Override
    public Field<String> field2() {
        return Fournisseur.FOURNISSEUR.V_RAISON_SOC;
    }

    @Override
    public Field<Integer> field3() {
        return Fournisseur.FOURNISSEUR.I_ADRESSE_ID;
    }

    @Override
    public Integer component1() {
        return getIFournisseurId();
    }

    @Override
    public String component2() {
        return getVRaisonSoc();
    }

    @Override
    public Integer component3() {
        return getIAdresseId();
    }

    @Override
    public Integer value1() {
        return getIFournisseurId();
    }

    @Override
    public String value2() {
        return getVRaisonSoc();
    }

    @Override
    public Integer value3() {
        return getIAdresseId();
    }

    @Override
    public FournisseurRecord value1(Integer value) {
        setIFournisseurId(value);
        return this;
    }

    @Override
    public FournisseurRecord value2(String value) {
        setVRaisonSoc(value);
        return this;
    }

    @Override
    public FournisseurRecord value3(Integer value) {
        setIAdresseId(value);
        return this;
    }

    @Override
    public FournisseurRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FournisseurRecord
     */
    public FournisseurRecord() {
        super(Fournisseur.FOURNISSEUR);
    }

    /**
     * Create a detached, initialised FournisseurRecord
     */
    public FournisseurRecord(Integer iFournisseurId, String vRaisonSoc, Integer iAdresseId) {
        super(Fournisseur.FOURNISSEUR);

        set(0, iFournisseurId);
        set(1, vRaisonSoc);
        set(2, iAdresseId);
    }
}
