/*
 * This file is generated by jOOQ.
 */
package org.jooq.model.madera.tables.records;


import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.model.madera.tables.Module;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModuleRecord extends UpdatableRecordImpl<ModuleRecord> implements Record7<Integer, Integer, Integer, String, String, String, Boolean> {

    private static final long serialVersionUID = -1122403818;

    /**
     * Setter for <code>madera.module.i_module_id</code>.
     */
    public void setIModuleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>madera.module.i_module_id</code>.
     */
    public Integer getIModuleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>madera.module.i_gammes_id</code>.
     */
    public void setIGammesId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>madera.module.i_gammes_id</code>.
     */
    public Integer getIGammesId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>madera.module.i_module_referentiel_id</code>.
     */
    public void setIModuleReferentielId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>madera.module.i_module_referentiel_id</code>.
     */
    public Integer getIModuleReferentielId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>madera.module.v_nom</code>.
     */
    public void setVNom(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>madera.module.v_nom</code>.
     */
    public String getVNom() {
        return (String) get(3);
    }

    /**
     * Setter for <code>madera.module.v_angle</code>.
     */
    public void setVAngle(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>madera.module.v_angle</code>.
     */
    public String getVAngle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>madera.module.v_nature_module</code>.
     */
    public void setVNatureModule(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>madera.module.v_nature_module</code>.
     */
    public String getVNatureModule() {
        return (String) get(5);
    }

    /**
     * Setter for <code>madera.module.b_modele</code>.
     */
    public void setBModele(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>madera.module.b_modele</code>.
     */
    public Boolean getBModele() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, Integer, String, String, String, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, Integer, String, String, String, Boolean> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Module.MODULE.I_MODULE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Module.MODULE.I_GAMMES_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Module.MODULE.I_MODULE_REFERENTIEL_ID;
    }

    @Override
    public Field<String> field4() {
        return Module.MODULE.V_NOM;
    }

    @Override
    public Field<String> field5() {
        return Module.MODULE.V_ANGLE;
    }

    @Override
    public Field<String> field6() {
        return Module.MODULE.V_NATURE_MODULE;
    }

    @Override
    public Field<Boolean> field7() {
        return Module.MODULE.B_MODELE;
    }

    @Override
    public Integer component1() {
        return getIModuleId();
    }

    @Override
    public Integer component2() {
        return getIGammesId();
    }

    @Override
    public Integer component3() {
        return getIModuleReferentielId();
    }

    @Override
    public String component4() {
        return getVNom();
    }

    @Override
    public String component5() {
        return getVAngle();
    }

    @Override
    public String component6() {
        return getVNatureModule();
    }

    @Override
    public Boolean component7() {
        return getBModele();
    }

    @Override
    public Integer value1() {
        return getIModuleId();
    }

    @Override
    public Integer value2() {
        return getIGammesId();
    }

    @Override
    public Integer value3() {
        return getIModuleReferentielId();
    }

    @Override
    public String value4() {
        return getVNom();
    }

    @Override
    public String value5() {
        return getVAngle();
    }

    @Override
    public String value6() {
        return getVNatureModule();
    }

    @Override
    public Boolean value7() {
        return getBModele();
    }

    @Override
    public ModuleRecord value1(Integer value) {
        setIModuleId(value);
        return this;
    }

    @Override
    public ModuleRecord value2(Integer value) {
        setIGammesId(value);
        return this;
    }

    @Override
    public ModuleRecord value3(Integer value) {
        setIModuleReferentielId(value);
        return this;
    }

    @Override
    public ModuleRecord value4(String value) {
        setVNom(value);
        return this;
    }

    @Override
    public ModuleRecord value5(String value) {
        setVAngle(value);
        return this;
    }

    @Override
    public ModuleRecord value6(String value) {
        setVNatureModule(value);
        return this;
    }

    @Override
    public ModuleRecord value7(Boolean value) {
        setBModele(value);
        return this;
    }

    @Override
    public ModuleRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6, Boolean value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModuleRecord
     */
    public ModuleRecord() {
        super(Module.MODULE);
    }

    /**
     * Create a detached, initialised ModuleRecord
     */
    public ModuleRecord(Integer iModuleId, Integer iGammesId, Integer iModuleReferentielId, String vNom, String vAngle, String vNatureModule, Boolean bModele) {
        super(Module.MODULE);

        set(0, iModuleId);
        set(1, iGammesId);
        set(2, iModuleReferentielId);
        set(3, vNom);
        set(4, vAngle);
        set(5, vNatureModule);
        set(6, bModele);
    }
}
