/*
 * This file is generated by jOOQ.
 */
package org.jooq.model.madera.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.model.madera.Indexes;
import org.jooq.model.madera.Keys;
import org.jooq.model.madera.Madera;
import org.jooq.model.madera.tables.records.GammesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gammes extends TableImpl<GammesRecord> {

    private static final long serialVersionUID = -1489217381;

    /**
     * The reference instance of <code>madera.gammes</code>
     */
    public static final Gammes GAMMES = new Gammes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GammesRecord> getRecordType() {
        return GammesRecord.class;
    }

    /**
     * The column <code>madera.gammes.i_gammes_id</code>.
     */
    public final TableField<GammesRecord, Integer> I_GAMMES_ID = createField(DSL.name("i_gammes_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>madera.gammes.v_libelle_gammes</code>.
     */
    public final TableField<GammesRecord, String> V_LIBELLE_GAMMES = createField(DSL.name("v_libelle_gammes"), org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * Create a <code>madera.gammes</code> table reference
     */
    public Gammes() {
        this(DSL.name("gammes"), null);
    }

    /**
     * Create an aliased <code>madera.gammes</code> table reference
     */
    public Gammes(String alias) {
        this(DSL.name(alias), GAMMES);
    }

    /**
     * Create an aliased <code>madera.gammes</code> table reference
     */
    public Gammes(Name alias) {
        this(alias, GAMMES);
    }

    private Gammes(Name alias, Table<GammesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Gammes(Name alias, Table<GammesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Gammes(Table<O> child, ForeignKey<O, GammesRecord> key) {
        super(child, key, GAMMES);
    }

    @Override
    public Schema getSchema() {
        return Madera.MADERA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GAMMES_PKEY);
    }

    @Override
    public UniqueKey<GammesRecord> getPrimaryKey() {
        return Keys.GAMMES_PKEY;
    }

    @Override
    public List<UniqueKey<GammesRecord>> getKeys() {
        return Arrays.<UniqueKey<GammesRecord>>asList(Keys.GAMMES_PKEY);
    }

    @Override
    public Gammes as(String alias) {
        return new Gammes(DSL.name(alias), this);
    }

    @Override
    public Gammes as(Name alias) {
        return new Gammes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Gammes rename(String name) {
        return new Gammes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Gammes rename(Name name) {
        return new Gammes(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
