/*
 * This file is generated by jOOQ.
 */
package org.jooq.model.madera.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.model.madera.Indexes;
import org.jooq.model.madera.Keys;
import org.jooq.model.madera.Madera;
import org.jooq.model.madera.tables.records.ModuleReferentielRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModuleReferentiel extends TableImpl<ModuleReferentielRecord> {

    private static final long serialVersionUID = 1821482634;

    /**
     * The reference instance of <code>madera.module_referentiel</code>
     */
    public static final ModuleReferentiel MODULE_REFERENTIEL = new ModuleReferentiel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ModuleReferentielRecord> getRecordType() {
        return ModuleReferentielRecord.class;
    }

    /**
     * The column <code>madera.module_referentiel.i_module_referentiel_id</code>.
     */
    public final TableField<ModuleReferentielRecord, Integer> I_MODULE_REFERENTIEL_ID = createField(DSL.name("i_module_referentiel_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>madera.module_referentiel.v_caracteristique</code>.
     */
    public final TableField<ModuleReferentielRecord, String> V_CARACTERISTIQUE = createField(DSL.name("v_caracteristique"), org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>madera.module_referentiel.v_unite_usage</code>.
     */
    public final TableField<ModuleReferentielRecord, String> V_UNITE_USAGE = createField(DSL.name("v_unite_usage"), org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * Create a <code>madera.module_referentiel</code> table reference
     */
    public ModuleReferentiel() {
        this(DSL.name("module_referentiel"), null);
    }

    /**
     * Create an aliased <code>madera.module_referentiel</code> table reference
     */
    public ModuleReferentiel(String alias) {
        this(DSL.name(alias), MODULE_REFERENTIEL);
    }

    /**
     * Create an aliased <code>madera.module_referentiel</code> table reference
     */
    public ModuleReferentiel(Name alias) {
        this(alias, MODULE_REFERENTIEL);
    }

    private ModuleReferentiel(Name alias, Table<ModuleReferentielRecord> aliased) {
        this(alias, aliased, null);
    }

    private ModuleReferentiel(Name alias, Table<ModuleReferentielRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ModuleReferentiel(Table<O> child, ForeignKey<O, ModuleReferentielRecord> key) {
        super(child, key, MODULE_REFERENTIEL);
    }

    @Override
    public Schema getSchema() {
        return Madera.MADERA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MODULE_REFERENTIEL_PKEY);
    }

    @Override
    public UniqueKey<ModuleReferentielRecord> getPrimaryKey() {
        return Keys.MODULE_REFERENTIEL_PKEY;
    }

    @Override
    public List<UniqueKey<ModuleReferentielRecord>> getKeys() {
        return Arrays.<UniqueKey<ModuleReferentielRecord>>asList(Keys.MODULE_REFERENTIEL_PKEY);
    }

    @Override
    public ModuleReferentiel as(String alias) {
        return new ModuleReferentiel(DSL.name(alias), this);
    }

    @Override
    public ModuleReferentiel as(Name alias) {
        return new ModuleReferentiel(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ModuleReferentiel rename(String name) {
        return new ModuleReferentiel(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ModuleReferentiel rename(Name name) {
        return new ModuleReferentiel(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
