/*
 * This file is generated by jOOQ.
 */
package com.madera.jooq.tables;


import com.madera.jooq.Indexes;
import com.madera.jooq.Keys;
import com.madera.jooq.Madera;
import com.madera.jooq.tables.records.ProjetProduitsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjetProduits extends TableImpl<ProjetProduitsRecord> {

    private static final long serialVersionUID = 1227053940;

    /**
     * The reference instance of <code>madera.projet_produits</code>
     */
    public static final ProjetProduits PROJET_PRODUITS = new ProjetProduits();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProjetProduitsRecord> getRecordType() {
        return ProjetProduitsRecord.class;
    }

    /**
     * The column <code>madera.projet_produits.i_projet_id</code>.
     */
    public final TableField<ProjetProduitsRecord, Integer> I_PROJET_ID = createField(DSL.name("i_projet_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>madera.projet_produits.i_produit_id</code>.
     */
    public final TableField<ProjetProduitsRecord, Integer> I_PRODUIT_ID = createField(DSL.name("i_produit_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>madera.projet_produits</code> table reference
     */
    public ProjetProduits() {
        this(DSL.name("projet_produits"), null);
    }

    /**
     * Create an aliased <code>madera.projet_produits</code> table reference
     */
    public ProjetProduits(String alias) {
        this(DSL.name(alias), PROJET_PRODUITS);
    }

    /**
     * Create an aliased <code>madera.projet_produits</code> table reference
     */
    public ProjetProduits(Name alias) {
        this(alias, PROJET_PRODUITS);
    }

    private ProjetProduits(Name alias, Table<ProjetProduitsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProjetProduits(Name alias, Table<ProjetProduitsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ProjetProduits(Table<O> child, ForeignKey<O, ProjetProduitsRecord> key) {
        super(child, key, PROJET_PRODUITS);
    }

    @Override
    public Schema getSchema() {
        return Madera.MADERA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FK_MODULE_IDX, Indexes.PROJET_PRODUITS_PKEY);
    }

    @Override
    public UniqueKey<ProjetProduitsRecord> getPrimaryKey() {
        return Keys.PROJET_PRODUITS_PKEY;
    }

    @Override
    public List<UniqueKey<ProjetProduitsRecord>> getKeys() {
        return Arrays.<UniqueKey<ProjetProduitsRecord>>asList(Keys.PROJET_PRODUITS_PKEY);
    }

    @Override
    public List<ForeignKey<ProjetProduitsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ProjetProduitsRecord, ?>>asList(Keys.PROJET_PRODUITS__FK_PROJET_2, Keys.PROJET_PRODUITS__FK_PROJET_PRODUITS);
    }

    public Projet projet() {
        return new Projet(this, Keys.PROJET_PRODUITS__FK_PROJET_2);
    }

    public Produit produit() {
        return new Produit(this, Keys.PROJET_PRODUITS__FK_PROJET_PRODUITS);
    }

    @Override
    public ProjetProduits as(String alias) {
        return new ProjetProduits(DSL.name(alias), this);
    }

    @Override
    public ProjetProduits as(Name alias) {
        return new ProjetProduits(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjetProduits rename(String name) {
        return new ProjetProduits(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjetProduits rename(Name name) {
        return new ProjetProduits(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
