/*
 * This file is generated by jOOQ.
 */
package com.madera.jooq.tables.records;


import com.madera.jooq.tables.Adresse;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdresseRecord extends UpdatableRecordImpl<AdresseRecord> implements Record6<Integer, String, String, String, String, String> {

    private static final long serialVersionUID = -1569018437;

    /**
     * Setter for <code>madera.adresse.i_adresse_id</code>.
     */
    public void setIAdresseId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>madera.adresse.i_adresse_id</code>.
     */
    public Integer getIAdresseId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>madera.adresse.v_ville</code>.
     */
    public void setVVille(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>madera.adresse.v_ville</code>.
     */
    public String getVVille() {
        return (String) get(1);
    }

    /**
     * Setter for <code>madera.adresse.v_code_postale</code>.
     */
    public void setVCodePostale(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>madera.adresse.v_code_postale</code>.
     */
    public String getVCodePostale() {
        return (String) get(2);
    }

    /**
     * Setter for <code>madera.adresse.v_rue</code>.
     */
    public void setVRue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>madera.adresse.v_rue</code>.
     */
    public String getVRue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>madera.adresse.v_complement</code>.
     */
    public void setVComplement(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>madera.adresse.v_complement</code>.
     */
    public String getVComplement() {
        return (String) get(4);
    }

    /**
     * Setter for <code>madera.adresse.v_numero</code>.
     */
    public void setVNumero(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>madera.adresse.v_numero</code>.
     */
    public String getVNumero() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Adresse.ADRESSE.I_ADRESSE_ID;
    }

    @Override
    public Field<String> field2() {
        return Adresse.ADRESSE.V_VILLE;
    }

    @Override
    public Field<String> field3() {
        return Adresse.ADRESSE.V_CODE_POSTALE;
    }

    @Override
    public Field<String> field4() {
        return Adresse.ADRESSE.V_RUE;
    }

    @Override
    public Field<String> field5() {
        return Adresse.ADRESSE.V_COMPLEMENT;
    }

    @Override
    public Field<String> field6() {
        return Adresse.ADRESSE.V_NUMERO;
    }

    @Override
    public Integer component1() {
        return getIAdresseId();
    }

    @Override
    public String component2() {
        return getVVille();
    }

    @Override
    public String component3() {
        return getVCodePostale();
    }

    @Override
    public String component4() {
        return getVRue();
    }

    @Override
    public String component5() {
        return getVComplement();
    }

    @Override
    public String component6() {
        return getVNumero();
    }

    @Override
    public Integer value1() {
        return getIAdresseId();
    }

    @Override
    public String value2() {
        return getVVille();
    }

    @Override
    public String value3() {
        return getVCodePostale();
    }

    @Override
    public String value4() {
        return getVRue();
    }

    @Override
    public String value5() {
        return getVComplement();
    }

    @Override
    public String value6() {
        return getVNumero();
    }

    @Override
    public AdresseRecord value1(Integer value) {
        setIAdresseId(value);
        return this;
    }

    @Override
    public AdresseRecord value2(String value) {
        setVVille(value);
        return this;
    }

    @Override
    public AdresseRecord value3(String value) {
        setVCodePostale(value);
        return this;
    }

    @Override
    public AdresseRecord value4(String value) {
        setVRue(value);
        return this;
    }

    @Override
    public AdresseRecord value5(String value) {
        setVComplement(value);
        return this;
    }

    @Override
    public AdresseRecord value6(String value) {
        setVNumero(value);
        return this;
    }

    @Override
    public AdresseRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdresseRecord
     */
    public AdresseRecord() {
        super(Adresse.ADRESSE);
    }

    /**
     * Create a detached, initialised AdresseRecord
     */
    public AdresseRecord(Integer iAdresseId, String vVille, String vCodePostale, String vRue, String vComplement, String vNumero) {
        super(Adresse.ADRESSE);

        set(0, iAdresseId);
        set(1, vVille);
        set(2, vCodePostale);
        set(3, vRue);
        set(4, vComplement);
        set(5, vNumero);
    }
}
