/*
 * This file is generated by jOOQ.
 */
package com.madera.jooq.tables.records;


import com.madera.jooq.tables.ClientAdresse;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientAdresseRecord extends TableRecordImpl<ClientAdresseRecord> implements Record3<Integer, Integer, Boolean> {

    private static final long serialVersionUID = -449327563;

    /**
     * Setter for <code>madera.client_adresse.i_client_id</code>.
     */
    public void setIClientId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>madera.client_adresse.i_client_id</code>.
     */
    public Integer getIClientId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>madera.client_adresse.i_adresse_id</code>.
     */
    public void setIAdresseId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>madera.client_adresse.i_adresse_id</code>.
     */
    public Integer getIAdresseId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>madera.client_adresse.b_adresse_facturation</code>.
     */
    public void setBAdresseFacturation(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>madera.client_adresse.b_adresse_facturation</code>.
     */
    public Boolean getBAdresseFacturation() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Boolean> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ClientAdresse.CLIENT_ADRESSE.I_CLIENT_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ClientAdresse.CLIENT_ADRESSE.I_ADRESSE_ID;
    }

    @Override
    public Field<Boolean> field3() {
        return ClientAdresse.CLIENT_ADRESSE.B_ADRESSE_FACTURATION;
    }

    @Override
    public Integer component1() {
        return getIClientId();
    }

    @Override
    public Integer component2() {
        return getIAdresseId();
    }

    @Override
    public Boolean component3() {
        return getBAdresseFacturation();
    }

    @Override
    public Integer value1() {
        return getIClientId();
    }

    @Override
    public Integer value2() {
        return getIAdresseId();
    }

    @Override
    public Boolean value3() {
        return getBAdresseFacturation();
    }

    @Override
    public ClientAdresseRecord value1(Integer value) {
        setIClientId(value);
        return this;
    }

    @Override
    public ClientAdresseRecord value2(Integer value) {
        setIAdresseId(value);
        return this;
    }

    @Override
    public ClientAdresseRecord value3(Boolean value) {
        setBAdresseFacturation(value);
        return this;
    }

    @Override
    public ClientAdresseRecord values(Integer value1, Integer value2, Boolean value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientAdresseRecord
     */
    public ClientAdresseRecord() {
        super(ClientAdresse.CLIENT_ADRESSE);
    }

    /**
     * Create a detached, initialised ClientAdresseRecord
     */
    public ClientAdresseRecord(Integer iClientId, Integer iAdresseId, Boolean bAdresseFacturation) {
        super(ClientAdresse.CLIENT_ADRESSE);

        set(0, iClientId);
        set(1, iAdresseId);
        set(2, bAdresseFacturation);
    }
}
