/*
 * This file is generated by jOOQ.
 */
package com.madera.jooq.tables.records;


import com.madera.jooq.tables.Gammes;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GammesRecord extends UpdatableRecordImpl<GammesRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 672933965;

    /**
     * Setter for <code>madera.gammes.i_gammes_id</code>.
     */
    public void setIGammesId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>madera.gammes.i_gammes_id</code>.
     */
    public Integer getIGammesId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>madera.gammes.v_libelle_gammes</code>.
     */
    public void setVLibelleGammes(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>madera.gammes.v_libelle_gammes</code>.
     */
    public String getVLibelleGammes() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Gammes.GAMMES.I_GAMMES_ID;
    }

    @Override
    public Field<String> field2() {
        return Gammes.GAMMES.V_LIBELLE_GAMMES;
    }

    @Override
    public Integer component1() {
        return getIGammesId();
    }

    @Override
    public String component2() {
        return getVLibelleGammes();
    }

    @Override
    public Integer value1() {
        return getIGammesId();
    }

    @Override
    public String value2() {
        return getVLibelleGammes();
    }

    @Override
    public GammesRecord value1(Integer value) {
        setIGammesId(value);
        return this;
    }

    @Override
    public GammesRecord value2(String value) {
        setVLibelleGammes(value);
        return this;
    }

    @Override
    public GammesRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GammesRecord
     */
    public GammesRecord() {
        super(Gammes.GAMMES);
    }

    /**
     * Create a detached, initialised GammesRecord
     */
    public GammesRecord(Integer iGammesId, String vLibelleGammes) {
        super(Gammes.GAMMES);

        set(0, iGammesId);
        set(1, vLibelleGammes);
    }
}
