/*
 * This file is generated by jOOQ.
 */
package com.madera.jooq.tables.records;


import com.madera.jooq.tables.Module;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModuleRecord extends UpdatableRecordImpl<ModuleRecord> implements Record6<Integer, Integer, Integer, String, String, Double> {

    private static final long serialVersionUID = 1718512669;

    /**
     * Setter for <code>madera.module.i_module_id</code>.
     */
    public void setIModuleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>madera.module.i_module_id</code>.
     */
    public Integer getIModuleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>madera.module.i_gammes_id</code>.
     */
    public void setIGammesId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>madera.module.i_gammes_id</code>.
     */
    public Integer getIGammesId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>madera.module.i_module_referentiel_id</code>.
     */
    public void setIModuleReferentielId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>madera.module.i_module_referentiel_id</code>.
     */
    public Integer getIModuleReferentielId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>madera.module.v_nom</code>.
     */
    public void setVNom(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>madera.module.v_nom</code>.
     */
    public String getVNom() {
        return (String) get(3);
    }

    /**
     * Setter for <code>madera.module.v_nature_module</code>.
     */
    public void setVNatureModule(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>madera.module.v_nature_module</code>.
     */
    public String getVNatureModule() {
        return (String) get(4);
    }

    /**
     * Setter for <code>madera.module.f_prix_module</code>.
     */
    public void setFPrixModule(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>madera.module.f_prix_module</code>.
     */
    public Double getFPrixModule() {
        return (Double) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, String, String, Double> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, Integer, String, String, Double> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Module.MODULE.I_MODULE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Module.MODULE.I_GAMMES_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Module.MODULE.I_MODULE_REFERENTIEL_ID;
    }

    @Override
    public Field<String> field4() {
        return Module.MODULE.V_NOM;
    }

    @Override
    public Field<String> field5() {
        return Module.MODULE.V_NATURE_MODULE;
    }

    @Override
    public Field<Double> field6() {
        return Module.MODULE.F_PRIX_MODULE;
    }

    @Override
    public Integer component1() {
        return getIModuleId();
    }

    @Override
    public Integer component2() {
        return getIGammesId();
    }

    @Override
    public Integer component3() {
        return getIModuleReferentielId();
    }

    @Override
    public String component4() {
        return getVNom();
    }

    @Override
    public String component5() {
        return getVNatureModule();
    }

    @Override
    public Double component6() {
        return getFPrixModule();
    }

    @Override
    public Integer value1() {
        return getIModuleId();
    }

    @Override
    public Integer value2() {
        return getIGammesId();
    }

    @Override
    public Integer value3() {
        return getIModuleReferentielId();
    }

    @Override
    public String value4() {
        return getVNom();
    }

    @Override
    public String value5() {
        return getVNatureModule();
    }

    @Override
    public Double value6() {
        return getFPrixModule();
    }

    @Override
    public ModuleRecord value1(Integer value) {
        setIModuleId(value);
        return this;
    }

    @Override
    public ModuleRecord value2(Integer value) {
        setIGammesId(value);
        return this;
    }

    @Override
    public ModuleRecord value3(Integer value) {
        setIModuleReferentielId(value);
        return this;
    }

    @Override
    public ModuleRecord value4(String value) {
        setVNom(value);
        return this;
    }

    @Override
    public ModuleRecord value5(String value) {
        setVNatureModule(value);
        return this;
    }

    @Override
    public ModuleRecord value6(Double value) {
        setFPrixModule(value);
        return this;
    }

    @Override
    public ModuleRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, Double value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModuleRecord
     */
    public ModuleRecord() {
        super(Module.MODULE);
    }

    /**
     * Create a detached, initialised ModuleRecord
     */
    public ModuleRecord(Integer iModuleId, Integer iGammesId, Integer iModuleReferentielId, String vNom, String vNatureModule, Double fPrixModule) {
        super(Module.MODULE);

        set(0, iModuleId);
        set(1, iGammesId);
        set(2, iModuleReferentielId);
        set(3, vNom);
        set(4, vNatureModule);
        set(5, fPrixModule);
    }
}
