/*
 * This file is generated by jOOQ.
 */
package com.madera.jooq.tables.records;


import com.madera.jooq.tables.Produit;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProduitRecord extends UpdatableRecordImpl<ProduitRecord> implements Record5<Integer, String, Integer, Double, Boolean> {

    private static final long serialVersionUID = 1226124112;

    /**
     * Setter for <code>madera.produit.i_produit_id</code>.
     */
    public void setIProduitId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>madera.produit.i_produit_id</code>.
     */
    public Integer getIProduitId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>madera.produit.v_produit_nom</code>.
     */
    public void setVProduitNom(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>madera.produit.v_produit_nom</code>.
     */
    public String getVProduitNom() {
        return (String) get(1);
    }

    /**
     * Setter for <code>madera.produit.i_gammes_id</code>.
     */
    public void setIGammesId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>madera.produit.i_gammes_id</code>.
     */
    public Integer getIGammesId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>madera.produit.f_prix_produit</code>.
     */
    public void setFPrixProduit(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>madera.produit.f_prix_produit</code>.
     */
    public Double getFPrixProduit() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>madera.produit.b_modele</code>.
     */
    public void setBModele(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>madera.produit.b_modele</code>.
     */
    public Boolean getBModele() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Integer, Double, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Integer, Double, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Produit.PRODUIT.I_PRODUIT_ID;
    }

    @Override
    public Field<String> field2() {
        return Produit.PRODUIT.V_PRODUIT_NOM;
    }

    @Override
    public Field<Integer> field3() {
        return Produit.PRODUIT.I_GAMMES_ID;
    }

    @Override
    public Field<Double> field4() {
        return Produit.PRODUIT.F_PRIX_PRODUIT;
    }

    @Override
    public Field<Boolean> field5() {
        return Produit.PRODUIT.B_MODELE;
    }

    @Override
    public Integer component1() {
        return getIProduitId();
    }

    @Override
    public String component2() {
        return getVProduitNom();
    }

    @Override
    public Integer component3() {
        return getIGammesId();
    }

    @Override
    public Double component4() {
        return getFPrixProduit();
    }

    @Override
    public Boolean component5() {
        return getBModele();
    }

    @Override
    public Integer value1() {
        return getIProduitId();
    }

    @Override
    public String value2() {
        return getVProduitNom();
    }

    @Override
    public Integer value3() {
        return getIGammesId();
    }

    @Override
    public Double value4() {
        return getFPrixProduit();
    }

    @Override
    public Boolean value5() {
        return getBModele();
    }

    @Override
    public ProduitRecord value1(Integer value) {
        setIProduitId(value);
        return this;
    }

    @Override
    public ProduitRecord value2(String value) {
        setVProduitNom(value);
        return this;
    }

    @Override
    public ProduitRecord value3(Integer value) {
        setIGammesId(value);
        return this;
    }

    @Override
    public ProduitRecord value4(Double value) {
        setFPrixProduit(value);
        return this;
    }

    @Override
    public ProduitRecord value5(Boolean value) {
        setBModele(value);
        return this;
    }

    @Override
    public ProduitRecord values(Integer value1, String value2, Integer value3, Double value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProduitRecord
     */
    public ProduitRecord() {
        super(Produit.PRODUIT);
    }

    /**
     * Create a detached, initialised ProduitRecord
     */
    public ProduitRecord(Integer iProduitId, String vProduitNom, Integer iGammesId, Double fPrixProduit, Boolean bModele) {
        super(Produit.PRODUIT);

        set(0, iProduitId);
        set(1, vProduitNom);
        set(2, iGammesId);
        set(3, fPrixProduit);
        set(4, bModele);
    }
}
