/*
 * This file is generated by jOOQ.
 */
package com.madera.jooq.tables.records;


import com.madera.jooq.tables.Projet;

import java.sql.Date;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjetRecord extends UpdatableRecordImpl<ProjetRecord> implements Record8<Integer, Integer, String, String, Date, byte[], Integer, Double> {

    private static final long serialVersionUID = -573243107;

    /**
     * Setter for <code>madera.projet.i_projet_id</code>.
     */
    public void setIProjetId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>madera.projet.i_projet_id</code>.
     */
    public Integer getIProjetId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>madera.projet.i_client_id</code>.
     */
    public void setIClientId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>madera.projet.i_client_id</code>.
     */
    public Integer getIClientId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>madera.projet.v_nom_projet</code>.
     */
    public void setVNomProjet(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>madera.projet.v_nom_projet</code>.
     */
    public String getVNomProjet() {
        return (String) get(2);
    }

    /**
     * Setter for <code>madera.projet.v_ref_projet</code>.
     */
    public void setVRefProjet(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>madera.projet.v_ref_projet</code>.
     */
    public String getVRefProjet() {
        return (String) get(3);
    }

    /**
     * Setter for <code>madera.projet.d_date_projet</code>.
     */
    public void setDDateProjet(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>madera.projet.d_date_projet</code>.
     */
    public Date getDDateProjet() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>madera.projet.v_signature_projet</code>.
     */
    public void setVSignatureProjet(byte... value) {
        set(5, value);
    }

    /**
     * Getter for <code>madera.projet.v_signature_projet</code>.
     */
    public byte[] getVSignatureProjet() {
        return (byte[]) get(5);
    }

    /**
     * Setter for <code>madera.projet.i_devis_etat_id</code>.
     */
    public void setIDevisEtatId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>madera.projet.i_devis_etat_id</code>.
     */
    public Integer getIDevisEtatId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>madera.projet.f_prix</code>.
     */
    public void setFPrix(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>madera.projet.f_prix</code>.
     */
    public Double getFPrix() {
        return (Double) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, String, String, Date, byte[], Integer, Double> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, String, String, Date, byte[], Integer, Double> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Projet.PROJET.I_PROJET_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Projet.PROJET.I_CLIENT_ID;
    }

    @Override
    public Field<String> field3() {
        return Projet.PROJET.V_NOM_PROJET;
    }

    @Override
    public Field<String> field4() {
        return Projet.PROJET.V_REF_PROJET;
    }

    @Override
    public Field<Date> field5() {
        return Projet.PROJET.D_DATE_PROJET;
    }

    @Override
    public Field<byte[]> field6() {
        return Projet.PROJET.V_SIGNATURE_PROJET;
    }

    @Override
    public Field<Integer> field7() {
        return Projet.PROJET.I_DEVIS_ETAT_ID;
    }

    @Override
    public Field<Double> field8() {
        return Projet.PROJET.F_PRIX;
    }

    @Override
    public Integer component1() {
        return getIProjetId();
    }

    @Override
    public Integer component2() {
        return getIClientId();
    }

    @Override
    public String component3() {
        return getVNomProjet();
    }

    @Override
    public String component4() {
        return getVRefProjet();
    }

    @Override
    public Date component5() {
        return getDDateProjet();
    }

    @Override
    public byte[] component6() {
        return getVSignatureProjet();
    }

    @Override
    public Integer component7() {
        return getIDevisEtatId();
    }

    @Override
    public Double component8() {
        return getFPrix();
    }

    @Override
    public Integer value1() {
        return getIProjetId();
    }

    @Override
    public Integer value2() {
        return getIClientId();
    }

    @Override
    public String value3() {
        return getVNomProjet();
    }

    @Override
    public String value4() {
        return getVRefProjet();
    }

    @Override
    public Date value5() {
        return getDDateProjet();
    }

    @Override
    public byte[] value6() {
        return getVSignatureProjet();
    }

    @Override
    public Integer value7() {
        return getIDevisEtatId();
    }

    @Override
    public Double value8() {
        return getFPrix();
    }

    @Override
    public ProjetRecord value1(Integer value) {
        setIProjetId(value);
        return this;
    }

    @Override
    public ProjetRecord value2(Integer value) {
        setIClientId(value);
        return this;
    }

    @Override
    public ProjetRecord value3(String value) {
        setVNomProjet(value);
        return this;
    }

    @Override
    public ProjetRecord value4(String value) {
        setVRefProjet(value);
        return this;
    }

    @Override
    public ProjetRecord value5(Date value) {
        setDDateProjet(value);
        return this;
    }

    @Override
    public ProjetRecord value6(byte... value) {
        setVSignatureProjet(value);
        return this;
    }

    @Override
    public ProjetRecord value7(Integer value) {
        setIDevisEtatId(value);
        return this;
    }

    @Override
    public ProjetRecord value8(Double value) {
        setFPrix(value);
        return this;
    }

    @Override
    public ProjetRecord values(Integer value1, Integer value2, String value3, String value4, Date value5, byte[] value6, Integer value7, Double value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjetRecord
     */
    public ProjetRecord() {
        super(Projet.PROJET);
    }

    /**
     * Create a detached, initialised ProjetRecord
     */
    public ProjetRecord(Integer iProjetId, Integer iClientId, String vNomProjet, String vRefProjet, Date dDateProjet, byte[] vSignatureProjet, Integer iDevisEtatId, Double fPrix) {
        super(Projet.PROJET);

        set(0, iProjetId);
        set(1, iClientId);
        set(2, vNomProjet);
        set(3, vRefProjet);
        set(4, dDateProjet);
        set(5, vSignatureProjet);
        set(6, iDevisEtatId);
        set(7, fPrix);
    }
}
