/*
 * This file is generated by jOOQ.
 */
package com.madera.jooq.tables.records;


import com.madera.jooq.tables.Role;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleRecord extends UpdatableRecordImpl<RoleRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 32840909;

    /**
     * Setter for <code>madera.role.i_role_id</code>.
     */
    public void setIRoleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>madera.role.i_role_id</code>.
     */
    public Integer getIRoleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>madera.role.v_libelle_role</code>.
     */
    public void setVLibelleRole(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>madera.role.v_libelle_role</code>.
     */
    public String getVLibelleRole() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Role.ROLE.I_ROLE_ID;
    }

    @Override
    public Field<String> field2() {
        return Role.ROLE.V_LIBELLE_ROLE;
    }

    @Override
    public Integer component1() {
        return getIRoleId();
    }

    @Override
    public String component2() {
        return getVLibelleRole();
    }

    @Override
    public Integer value1() {
        return getIRoleId();
    }

    @Override
    public String value2() {
        return getVLibelleRole();
    }

    @Override
    public RoleRecord value1(Integer value) {
        setIRoleId(value);
        return this;
    }

    @Override
    public RoleRecord value2(String value) {
        setVLibelleRole(value);
        return this;
    }

    @Override
    public RoleRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleRecord
     */
    public RoleRecord() {
        super(Role.ROLE);
    }

    /**
     * Create a detached, initialised RoleRecord
     */
    public RoleRecord(Integer iRoleId, String vLibelleRole) {
        super(Role.ROLE);

        set(0, iRoleId);
        set(1, vLibelleRole);
    }
}
